require 'json'

require Pod::Executable.execute_command(
  'node',
  ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb", { paths: [process.argv[1]] })', __dir__]
).strip

platform :ios, '16.0'

use_frameworks! :linkage => :static
prepare_react_native_project!

target 'Realmreader' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

post_install do |installer|
  config = use_native_modules!

  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # iOS deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'

      # Force dSYM for Hermes
      if target.name.downcase.include?("hermes")
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

        # C++ std::thread fix
        config.build_settings['CPLUSPLUS_LANGUAGE_STANDARD'] = 'c++14'
        config.build_settings['CPLUSPLUS_LIBRARY'] = 'libc++'
      end
    end
  end
end
